version: "3"

services:
  zk:
    image: bobrik/zookeeper
    network_mode: host
    environment:
      ZK_CONFIG: tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
      ZK_ID: 1
  master:
    image: mesosphere/mesos-master:1.2.1
    network_mode: host
    pid: host
    userns_mode: host
    privileged: true
#    ports:
#      - "5050:5050"
    environment:
      MESOS_ZK: zk://${DOCKER_IP}:2181/mesos
      MESOS_QUORUM: 1
      MESOS_CLUSTER: docker-compose
#      MESOS_REGISTRY: replicated_log # default is in_memory for some reason
      MESOS_HOSTNAME: ${DOCKER_IP}
#      MESOS_ADVERTISE_IP: ${DOCKER_IP}
#      LIBPROCESS_IP: ${DOCKER_IP}
    depends_on:
      - zk

  slave-one:
    image: mesosphere/mesos-slave:1.2.1
    network_mode: host
    pid: host
    userns_mode: host
    privileged: true
#    ports:
#      - "5051:5051"
    environment:
      MESOS_MASTER: zk://${DOCKER_IP}:2181/mesos
      MESOS_CONTAINERIZERS: docker
      MESOS_PORT: 5051
      MESOS_RESOURCES: ports(*):[11000-11199]
      MESOS_HOSTNAME: ${DOCKER_IP}
#      LIBPROCESS_IP: ${DOCKER_IP}
      MESOS_ADVERTISE_IP: ${DOCKER_IP}
      MESOS_WORK_DIR: /tmp/mesos
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zk

  slave-two:
    image: mesosphere/mesos-slave:1.2.1
    network_mode: host
    pid: host
    userns_mode: host
    privileged: true
#    ports:
#      - "5051:5051"
    environment:
      MESOS_MASTER: zk://${DOCKER_IP}:2181/mesos
      MESOS_CONTAINERIZERS: docker
      MESOS_PORT: 5052
      MESOS_RESOURCES: ports(*):[11200-11499]
      MESOS_HOSTNAME: ${DOCKER_IP}
#      LIBPROCESS_IP: ${DOCKER_IP}
      MESOS_ADVERTISE_IP: ${DOCKER_IP}
      MESOS_WORK_DIR: /tmp/mesos
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zk