version: "3"

services:
  zk:
    image: zookeeper:3.4
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2188

  master:
    image: mesosphere/mesos-master:1.2.1
    entrypoint:
      - sh
      - -c
      - MESOS_HOSTNAME=$$(ip route | tail -n 1 | cut -d ' ' -f 12) mesos-master --registry=in_memory
    environment:
      MESOS_ZK: zk://zk:2188/mesos
      MESOS_QUORUM: 3
      MESOS_CLUSTER: docker-compose
    depends_on:
      - zk

  slave:
    image: mesosphere/mesos-slave:1.2.1
    privileged: true
    entrypoint:
      - sh
      - -c
      - service docker start;until docker run --rm hello-world; do echo "Waiting for docker";sleep 2; done;MESOS_HOSTNAME=$$(ip route | tail -n 1 | cut -d ' ' -f 12) mesos-slave
    environment:
      MESOS_MASTER: zk://zk:2188/mesos
      MESOS_CONTAINERIZERS: docker
      MESOS_RESOURCES: cpus(*):2;mem(*):1000
      MESOS_WORK_DIR: /tmp/mesos
    depends_on:
      - zk

  marathon:
    image: mesosphere/marathon:v1.3.10
    entrypoint:
      - sh 
      - -c
      - ./bin/start --disable_ha --http_port "8080" --hostname "$$(ip route | tail -n 1 | cut -d ' ' -f 12)"
    depends_on:
      - zk
    environment:
      - MARATHON_ZK=zk://zk:2188/marathon
      - MARATHON_MASTER=zk://zk:2188/mesos